import '../css/modules/_general.css';
import '../css/modules/_readMoreButton.css';
import '../css/modules/_home.css';
import '../css/modules/_projects.css';
import '../css/modules/_news.css';
import '../css/modules/_aboutsUs.css';
import '../css/modules/_careers.css';
import '../css/modules/_findUs.css';
import '../css/modules/_media.css';